---
- name: create backend directory
  become: yes
  file:
    path: ~/backend
    state: directory

- name: copy backend files
  become: yes
  copy:
    src: ~/project/artifact.tar.gz
    dest: ~/backend/artifact.tar.gz

- name: "Install dependencies"
  shell: |
    cd ~/backend-app
    npm i

- name: "Start backend application with PM2"
  shell: |
    cd ~/backend/dist
    pm2 stop default
    pm2 start main.js
    register: execute_node

- name: print message
  debug:
    msg: "{{ execute_node.stdout_lines }}"

- name: "Configure pm2 to start as service"
  become: true
  shell: |
    env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu